# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: namespace-b-app4
  labels: {{- include "hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "hello-world.selectorLabels" . | nindent 4 }}
